---
abstract: '(DEPRECATED) Send emails with Catalyst'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.0526, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-Email
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst: '2.99'
  Email::MIME: '0'
  Email::MIME::Creator: '0'
  Email::Send: '0'
  perl: '5.008'
resources:
  IRC: irc://irc.perl.org/#catalyst
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-Email
  repository: https://github.com/perl-catalyst/Catalyst-Plugin-Email.git
version: '0.09'
x_deprecated: 1
x_serialization_backend: 'CPAN::Meta::YAML version 0.017'

